In [118]:
import pandas as pd
import plotly.graph_objects as go

# Plot selected sites

In [119]:
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [120]:
#plot_sankey_hierarchy(production_df, columns_to_plot, html_output="data/MetalliCan/sites_for_lci_archetypes.html")

# Import cleaned MetalliCan data

In [121]:
from utils.data_manipulations import build_activity_name, add_site_id

In [122]:
# Pre-processed production table
production_df = pd.read_excel(r'data/MetalliCan/sites_for_lci.xlsx', sheet_name='prod_data')

In [123]:
# Add activitiy_name to production_df and site_id
production_df['activity_name'] = production_df.apply(lambda row: build_activity_name(row, production_df), axis=1)
production_df = add_site_id(production_df)

In [124]:
production_df

,main_id,facility_group_id,facility_name,facility_group_name,province,facility_type,mining_processing_type,npv,archetypes,biosphere_data?,...,Zn_conc,Pb_conc,Fe_conc,Pt_conc,Pd_conc,U_conc,Nb_conc,Au_conc,activity_name,site_id
0,AB-MAIN-d3a4aba9,<NA>,The Cobalt Refinery Company Inc.,NaN,Alberta,manufacturing,Refinery,Cold Evergreen Needleleaf Forest,Co hydrometallurgical refinery,NPRI+GHG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Refining at The Cobalt Refinery Company Inc.,AB-MAIN-d3a4aba9
1,BC-MAIN-3bb6b7cd,<NA>,Trail,NaN,British Columbia,manufacturing,Refinery,Cool Evergreen Needleleaf Forest,Zn refinery,NPRI+GHG+Water,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Refining at Trail,BC-MAIN-3bb6b7cd
2,BC-MAIN-3f490561,<NA>,Mount Polley,NaN,British Columbia,mining,"Open-pit, concentrator",Cold Evergreen Needleleaf Forest,"Porphyry sulfide, flotation-based",NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,Open-pit mining and beneficiation at Mount Polley,BC-MAIN-3f490561
3,BC-MAIN-4724f4ba,<NA>,Elk,NaN,British Columbia,mining,Open-pit,Cold Evergreen Needleleaf Forest,Free-milling,Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.124287,Open-pit mining at Elk,BC-MAIN-4724f4ba
4,BC-MAIN-599152a0,<NA>,Copper Mountain,NaN,British Columbia,mining,"Open-pit, concentrator",Cool Evergreen Needleleaf Forest,"Porphyry sulfide, flotation-based",NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,Open-pit mining and beneficiation at Copper Mo...,BC-MAIN-599152a0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,<NA>,GRP-0a2c0d69,NaN,Meadowbank complex,Nunavut,mining,"Open-pit, underground",NaN,Free-milling,NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,17.667601,Open-pit and underground mining at Meadowbank ...,GRP-0a2c0d69
62,<NA>,GRP-0d911886,NaN,Porcupine complex,Ontario,mining,"Open-pit, underground",NaN,Free-milling,NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,8.251949,Open-pit and underground mining at Porcupine c...,GRP-0d911886
63,<NA>,GRP-147b3123,NaN,Timmins Operation,Ontario,mining,"Underground, concentrator",NaN,Free-milling,NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,4.218015,Underground mining and beneficiation at Timmin...,GRP-147b3123
64,<NA>,GRP-14bfbb82,NaN,Seabee Gold Operation,Saskatchewan,mining,"Underground, concentrator",NaN,Free-milling,NPRI+GHG+Land,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,1.230080,Underground mining and beneficiation at Seabee...,GRP-14bfbb82
65,<NA>,GRP-a13779f8,NaN,Snow Lake,Manitoba,mining,"Underground, concentrator",NaN,Free-milling,NPRI+Land,...,69284.0,0.0,0.0,NaN,NaN,NaN,0.0,32.978787,Underground mining and beneficiation at Snow Lake,GRP-a13779f8

In [125]:
# Normalized MetalliCan tables per ore processed
# energy_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/energy_df.csv')
# material_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/material_df.csv')
# biosphere_ore_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/ore/biosphere_df.csv')

In [126]:
# Normalized MetalliCan tables per ore processed
energy_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/energy_df.csv')
material_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/material_df.csv')
biosphere_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/biosphere_df.csv')
land_stream_df = pd.read_csv(r'data/MetalliCan/data_for_lci_initialization/concentrate/land_df.csv')

In [127]:
energy_stream_df

,site_id,activity_name,mining_processing_type,archetypes,flow_type,subflow_type,value,unit,data_source,value_formula,concentrate,mass_conc,allocation_factor,facility_type,value_normalized,functional_unit,normalization_key,reference_mass_unit
0,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-milling-refactory,Energy,Acetylene,1.847565e+04,MJ,MetalliCan,MetalliCan,Au,0.920410,1.0,mining,20.073290,Doré,concentrate_economic,kg
1,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-milling-refactory,Energy,Aviation fuel,7.267611e+07,MJ,MetalliCan,MetalliCan,Au,0.920410,1.0,mining,78960.609903,Doré,concentrate_economic,kg
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-milling-refactory,Energy,Diesel,2.870424e+08,MJ,MetalliCan,MetalliCan,Au,0.920410,1.0,mining,311863.781032,Doré,concentrate_economic,kg
3,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-milling-refactory,Energy,Electricity consumption|Generated on-site,8.622512e+07,MJ,MetalliCan,MetalliCan,Au,0.920410,1.0,mining,93681.235616,Doré,concentrate_economic,kg
4,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,"Underground, concentrator",Hybrid free-milling-refactory,Energy,Electricity consumption|Grid electricity,5.690096e+08,MJ,MetalliCan,MetalliCan,Au,0.920410,1.0,mining,618213.376701,Doré,concentrate_economic,kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,QC-MAIN-a555d9b9,Underground mining and beneficiation at Niobec,"Underground, concentrator",Nb mine,Energy,Lpg|Stationary,2.334366e+05,L,Inference from CO2 (stationary lpg),(642.6510000000001 * 1e6) / 2753,Nb,113.257759,NaN,mining,NaN,Nb concentrate,concentrate_economic,kg
216,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Transport,6.363417e+06,L,Inference from CO2 (transport diesel),(17060.32142 * 1e6) / 2681,Ni,151450.000000,1.0,mining,0.042017,Ni concentrate,concentrate_economic,kg
217,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Diesel|Stationary,1.544615e+07,L,Inference from CO2 (stationary diesel),(41411.13374999999 * 1e6) / 2681,Ni,151450.000000,1.0,mining,0.101988,Ni concentrate,concentrate_economic,kg
218,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Natural Gas|Stationary,3.518363e+07,m3,Inference from CO2 (stationary natural_gas),(82822.26749999999 * 1e6) / 2354,Ni,151450.000000,1.0,mining,0.232312,Ni concentrate,concentrate_economic,kg
219,QC-MAIN-a97821c0,Underground mining and beneficiation at Raglan,"Underground, concentrator","Porphyry sulfide, flotation-based",Energy,Lpg|Stationary,5.014061e+06,L,Inference from CO2 (stationary lpg),(13803.71125 * 1e6) / 2753,Ni,151450.000000,1.0,mining,0.033107,Ni concentrate,concentrate_economic,kg

In [128]:
material_stream_df

,site_id,activity_name,mining_processing_type,archetypes,flow_type,subflow_type,value,unit,data_source,value_formula,...,mass_conc,allocation_factor,facility_type,value_normalized,value_min_normalized,value_mean_normalized,value_max_normalized,functional_unit,normalization_key,reference_mass_unit
0,QC-MAIN-b86f7d07,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator",Free-milling,Material use,Surface/underground emulsion & ANFO,2.968124e+03,t,MetalliCan,MetalliCan,...,3.516600,1.000000,mining,0.844032,NaN,NaN,NaN,Doré,concentrate_economic,kg
1,ON-MAIN-aeafbb59,Open-pit mining and beneficiation at Detour Lake,"Open-pit, concentrator",Free-milling,Material use,Explosives,1.626850e+04,t,MetalliCan,MetalliCan,...,24.008284,1.000000,mining,0.677620,NaN,NaN,NaN,Doré,concentrate_economic,kg
2,ON-MAIN-cb85213a,Underground mining and beneficiation at Eagle ...,"Underground, concentrator",Free-milling,Material use,Explosives,1.211000e+03,t,MetalliCan,MetalliCan,...,2.776051,1.000000,mining,0.436231,NaN,NaN,NaN,Doré,concentrate_economic,kg
3,QC-MAIN-6dc537e6,Underground mining and beneficiation at Éléonore,"Underground, concentrator",Free-milling,Material use,Cement,2.737400e+04,t,MetalliCan,MetalliCan,...,7.738900,1.000000,mining,3.537195,NaN,NaN,NaN,Doré,concentrate_economic,kg
4,QC-MAIN-6dc537e6,Underground mining and beneficiation at Éléonore,"Underground, concentrator",Free-milling,Material use,Grinding media,3.039900e+03,t,MetalliCan,MetalliCan,...,7.738900,1.000000,mining,0.392808,NaN,NaN,NaN,Doré,concentrate_economic,kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,GRP-147b3123,Underground mining and beneficiation at Timmin...,"Underground, concentrator",Free-milling,Material use,Tailings,-1.573996e+06,t,NaN,NaN,...,4.218015,1.000000,mining,-373.160269,NaN,NaN,NaN,Doré,concentrate_economic,kg
949,GRP-14bfbb82,Underground mining and beneficiation at Seabee...,"Underground, concentrator",Free-milling,Material use,Tailings,-1.219988e+05,t,NaN,NaN,...,1.230080,1.000000,mining,-99.179545,NaN,NaN,NaN,Doré,concentrate_economic,kg
950,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Material use,Tailings,-2.013811e+06,t,NaN,NaN,...,40513.333333,0.129040,mining,-0.006414,NaN,NaN,NaN,Cu concentrate,concentrate_economic,kg
951,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Material use,Tailings,-2.013811e+06,t,NaN,NaN,...,69284.000000,0.082492,mining,-0.002398,NaN,NaN,NaN,Zn concentrate,concentrate_economic,kg
952,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Material use,Tailings,-2.013811e+06,t,NaN,NaN,...,32.978787,0.788468,mining,-48.146845,NaN,NaN,NaN,Doré,concentrate_economic,kg

In [129]:
biosphere_stream_df

,site_id,activity_name,mining_processing_type,archetypes,compartment_name,substance_name,flow_direction,release_pathway,unit,value,data_source,value_formula,concentrate,mass_conc,allocation_factor,facility_type,value_normalized,functional_unit,normalization_key,reference_mass_unit
0,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-milling,Air,Ammonia (total),Emission,Stack Emissions,tonnes,0.63600,MetalliCan,MetalliCan,Au,7.253304,1.000000,mining,8.768417e-05,Doré,concentrate_economic,kg
1,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-milling,Air,Arsenic (and its compounds),Emission,Stack Emissions,kg,0.11600,MetalliCan,MetalliCan,Au,7.253304,1.000000,mining,1.599271e-05,Doré,concentrate_economic,kg
2,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-milling,Air,Carbon monoxide,Emission,Stack Emissions,tonnes,76.20800,MetalliCan,MetalliCan,Au,7.253304,1.000000,mining,1.050666e-02,Doré,concentrate_economic,kg
3,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-milling,Air,Chromium (and its compounds),Emission,Stack Emissions,tonnes,0.00105,MetalliCan,MetalliCan,Au,7.253304,1.000000,mining,1.447616e-07,Doré,concentrate_economic,kg
4,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,"Underground, concentrator",Free-milling,Air,Cobalt (and its compounds),Emission,Stack Emissions,kg,0.18000,MetalliCan,MetalliCan,Au,7.253304,1.000000,mining,2.481628e-05,Doré,concentrate_economic,kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Water,Nitrate ion in solution at pH >= 6.0,Emission,Direct Discharge,tonnes,15.64000,MetalliCan,MetalliCan,Zn,69284.000000,0.082492,mining,1.862165e-08,Zn concentrate,concentrate_economic,kg
2914,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Water,Nitrate ion in solution at pH >= 6.0,Emission,Direct Discharge,tonnes,15.64000,MetalliCan,MetalliCan,Au,32.978787,0.788468,mining,3.739262e-04,Doré,concentrate_economic,kg
2915,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Water,Nitrate ion in solution at pH >= 6.0,Emission,Waterbody,tonnes,0.00000,MetalliCan,MetalliCan,Cu,40513.333333,0.129040,mining,0.000000e+00,Cu concentrate,concentrate_economic,kg
2916,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Water,Nitrate ion in solution at pH >= 6.0,Emission,Waterbody,tonnes,0.00000,MetalliCan,MetalliCan,Zn,69284.000000,0.082492,mining,0.000000e+00,Zn concentrate,concentrate_economic,kg
2917,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,"Underground, concentrator",Free-milling,Water,Nitrate ion in solution at pH >= 6.0,Emission,Waterbody,tonnes,0.00000,MetalliCan,MetalliCan,Au,32.978787,0.788468,mining,0.000000e+00,Doré,concentrate_economic,kg

In [130]:
# Removing rows with value_normalized is NaN in the biosphere dfs
#biosphere_ore_df = biosphere_ore_df[~biosphere_ore_df['value_normalized'].isna()]
#biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e6

In [131]:
# For all the dfs, multiply the value_normalized to 10e3 to have values per kg
# energy_stream_df['value_normalized'] = energy_stream_df['value_normalized'] / 1e3
# material_stream_df['value_normalized'] = material_stream_df['value_normalized'] / 1e3
# material_stream_df['value_min_normalized'] = material_stream_df['value_min_normalized'] / 1e3
# material_stream_df['value_mean_normalized'] = material_stream_df['value_mean_normalized'] / 1e3
# material_stream_df['value_max_normalized'] = material_stream_df['value_max_normalized'] / 1e3
# biosphere_stream_df['value_normalized'] = biosphere_stream_df['value_normalized'] / 1e3
# land_stream_df['value_min_normalized'] = land_stream_df['value_min_normalized'] / 1e3
# land_stream_df['value_mean_normalized'] = land_stream_df['value_mean_normalized'] / 1e3
# land_stream_df['value_max_normalized'] = land_stream_df['value_max_normalized'] / 1e3

# Transform land_stream_df to have the same columns as biosphere_stream_df

In [132]:
# Drop rows where 'unit' = 'ha'
biosphere_stream_df = biosphere_stream_df[biosphere_stream_df['unit'] != 'ha']

In [133]:
def add_land_substance_name(df):
    """
    Add ecoinvent-style land use 'substance_name' column
    based on flow_type, npv and mining_processing_type.
    """

    import numpy as np

    out = df.copy()

    MANU_TYPES = {
        "Refinery",
        "Smelter, plant",
        "Smelter, refinery, plant",
    }

    is_manu = out["mining_processing_type"].isin(MANU_TYPES)

    out["substance_name"] = np.select(
        [
            out["flow_type"].eq("transformation_from"),
            out["flow_type"].eq("transformation_to") & is_manu,
            out["flow_type"].eq("transformation_to") & ~is_manu,
            out["flow_type"].eq("occupation") & is_manu,
            out["flow_type"].eq("occupation") & ~is_manu,
        ],
        [
            "Transformation, from " + out["npv"].astype(str),
            "Transformation, to manufacturing area",
            "Transformation, to mine area",
            "Occupation, manufacturing area",
            "Occupation, mine area",
        ],
        default=None,
    )

    return out

In [134]:
land_stream_df = add_land_substance_name(land_stream_df)

In [135]:
land_stream_df

,site_id,flow_type,functional_unit,normalization_key,allocation_factor,unit,activity_name,mining_processing_type,archetypes,npv,...,data_source,value_formula,amount_parameter,parameter_distribution,value_normalized,value_min_normalized,value_mean_normalized,value_max_normalized,reference_mass_unit,substance_name
0,BC-MAIN-3f490561,transformation_from,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.008741,NaN,NaN,NaN,kg,"Transformation, from Cold Evergreen Needleleaf..."
1,BC-MAIN-3f490561,transformation_to,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.008741,NaN,NaN,NaN,kg,"Transformation, to mine area"
2,BC-MAIN-3f490561,occupation,Cu concentrate,land_concentrate_economic,1.0,m2*year,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.174816,NaN,NaN,NaN,kg,"Occupation, mine area"
3,BC-MAIN-4724f4ba,transformation_from,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Free-milling,Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,167.650962,NaN,NaN,NaN,kg,"Transformation, from Cold Evergreen Needleleaf..."
4,BC-MAIN-4724f4ba,transformation_to,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Free-milling,Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,167.650962,NaN,NaN,NaN,kg,"Transformation, to mine area"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,ON-MAIN-f4fc3276,transformation_to,Doré,land_concentrate_economic,1.0,m2,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-milling,Unspecified NPV,...,Inference (underground range),"Uniform(5e5, 2e6)",NaN,"Uniform(5e5, 2e6)",NaN,20.375403,50.938507,81.501612,kg,"Transformation, to mine area"
176,ON-MAIN-f4fc3276,occupation,Doré,land_concentrate_economic,1.0,m2*year,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-milling,Unspecified NPV,...,Inference (underground range),"Uniform(5e5, 2e6)",NaN,"Uniform(5e5, 2e6)",NaN,407.508059,1018.770148,1630.032238,kg,"Occupation, mine area"
177,QC-MAIN-5ce331b8,transformation_from,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,0.000011,0.000011,0.000011,kg,"Transformation, from Unspecified NPV"
178,QC-MAIN-5ce331b8,transformation_to,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,0.000011,0.000011,0.000011,kg,"Transformation, to mine area"
179,QC-MAIN-5ce331b8,occupation,Ni concentrate,land_concentrate_economic,1.0,m2*year,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,0.000221,0.000221,0.000221,kg,"Occupation, mine area"

In [136]:
land_stream_df_t = land_stream_df

In [137]:
land_stream_df_t['value_min_normalized'].dtype

dtype('float64')

In [138]:
land_stream_df_t['value_min_normalized'] = land_stream_df_t['value_min_normalized'] / 1e3

In [139]:
land_stream_df_t

,site_id,flow_type,functional_unit,normalization_key,allocation_factor,unit,activity_name,mining_processing_type,archetypes,npv,...,data_source,value_formula,amount_parameter,parameter_distribution,value_normalized,value_min_normalized,value_mean_normalized,value_max_normalized,reference_mass_unit,substance_name
0,BC-MAIN-3f490561,transformation_from,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.008741,NaN,NaN,NaN,kg,"Transformation, from Cold Evergreen Needleleaf..."
1,BC-MAIN-3f490561,transformation_to,Cu concentrate,land_concentrate_economic,1.0,m2,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.008741,NaN,NaN,NaN,kg,"Transformation, to mine area"
2,BC-MAIN-3f490561,occupation,Cu concentrate,land_concentrate_economic,1.0,m2*year,Open-pit mining and beneficiation at Mount Polley,"Open-pit, concentrator","Porphyry sulfide, flotation-based",Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,0.174816,NaN,NaN,NaN,kg,"Occupation, mine area"
3,BC-MAIN-4724f4ba,transformation_from,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Free-milling,Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,167.650962,NaN,NaN,NaN,kg,"Transformation, from Cold Evergreen Needleleaf..."
4,BC-MAIN-4724f4ba,transformation_to,Doré,land_concentrate_economic,1.0,m2,Open-pit mining at Elk,Open-pit,Free-milling,Cold Evergreen Needleleaf Forest,...,MetalliCan,MetalliCan,NaN,NaN,167.650962,NaN,NaN,NaN,kg,"Transformation, to mine area"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,ON-MAIN-f4fc3276,transformation_to,Doré,land_concentrate_economic,1.0,m2,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-milling,Unspecified NPV,...,Inference (underground range),"Uniform(5e5, 2e6)",NaN,"Uniform(5e5, 2e6)",NaN,2.037540e-02,50.938507,81.501612,kg,"Transformation, to mine area"
176,ON-MAIN-f4fc3276,occupation,Doré,land_concentrate_economic,1.0,m2*year,Underground mining and beneficiation at Sugar ...,"Underground, concentrator",Free-milling,Unspecified NPV,...,Inference (underground range),"Uniform(5e5, 2e6)",NaN,"Uniform(5e5, 2e6)",NaN,4.075081e-01,1018.770148,1630.032238,kg,"Occupation, mine area"
177,QC-MAIN-5ce331b8,transformation_from,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,1.103493e-08,0.000011,0.000011,kg,"Transformation, from Unspecified NPV"
178,QC-MAIN-5ce331b8,transformation_to,Ni concentrate,land_concentrate_economic,1.0,m2,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,1.103493e-08,0.000011,0.000011,kg,"Transformation, to mine area"
179,QC-MAIN-5ce331b8,occupation,Ni concentrate,land_concentrate_economic,1.0,m2*year,Open-pit and underground mining and beneficiat...,"Open-pit, underground, concentrator","Porphyry sulfide, flotation-based",Unspecified NPV,...,Inference (open-pit model),(0.510 * 1082352.94117647) - 7.14e6,ore_processed_t,NaN,NaN,2.206986e-07,0.000221,0.000221,kg,"Occupation, mine area"

# Keeping only relevant columns

In [140]:
nrj_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'unit', 'value_normalized']
material_col = ['activity_name', 'functional_unit', 'site_id', 'subflow_type', 'unit', 'value_normalized', 'value_min_normalized', 'value_mean_normalized', 'value_max_normalized']
biosphere_col = ['activity_name', 'functional_unit', 'site_id', 'substance_name', 'unit', 'value_normalized', 'value_min_normalized', 'value_mean_normalized', 'value_max_normalized']

In [141]:
# Create columns for biosphere_df
biosphere_stream_df['value_min_normalized'] = ''
biosphere_stream_df['value_mean_normalized'] = ''
biosphere_stream_df['value_max_normalized'] = ''

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_23020\3297490019.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biosphere_stream_df['value_min_normalized'] = ''
C:\Users\mp_ma\AppData\Local\Temp\ipykernel_23020\3297490019.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biosphere_stream_df['value_mean_normalized'] = ''
C:\Users\mp_ma\AppData\Local\Temp\ipykernel_23020\3297490019.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biosphere_stream_df['value_max_normalized'] = ''

In [142]:
energy_stream_df = energy_stream_df[nrj_col]
material_stream_df = material_stream_df[material_col]
biosphere_stream_df = biosphere_stream_df[biosphere_col]
land_stream_df = land_stream_df[biosphere_col]

In [143]:
# Put energy_df and material_df together, and biosphere_df and land_df together
technosphere_stream_df = pd.concat([energy_stream_df, material_stream_df], ignore_index=True)
biosphere_stream_df = pd.concat([biosphere_stream_df, land_stream_df], ignore_index=True)

In [144]:
# Remove rows where value_normalized, value_min_normalized, value_mean_normalized and value_max_normalized are NaN
technosphere_stream_df = technosphere_stream_df[~technosphere_stream_df['value_normalized'].isna() | ~technosphere_stream_df['value_min_normalized'].isna() | ~technosphere_stream_df['value_mean_normalized'].isna() | ~technosphere_stream_df['value_max_normalized'].isna()]

In [145]:
# Add the province from the main_df to specify electricity location later
technosphere_stream_df = technosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')
biosphere_stream_df = biosphere_stream_df.merge(production_df[['site_id', 'province']], on=['site_id'], how='left')

In [146]:
# Remove rows where value_normalized, value_min_normalized, value_mean_normalized and value_max_normalized are NaN
technosphere_stream_df = technosphere_stream_df[~technosphere_stream_df['value_normalized'].isna() | ~technosphere_stream_df['value_min_normalized'].isna() | ~technosphere_stream_df['value_mean_normalized'].isna() | ~technosphere_stream_df['value_max_normalized'].isna()]

In [147]:
technosphere_stream_df

,activity_name,functional_unit,site_id,subflow_type,unit,value_normalized,value_min_normalized,value_mean_normalized,value_max_normalized,province
0,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Acetylene,MJ,20.073290,NaN,NaN,NaN,British Columbia
1,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Aviation fuel,MJ,78960.609903,NaN,NaN,NaN,British Columbia
2,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Diesel,MJ,311863.781032,NaN,NaN,NaN,British Columbia
3,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Generated on-site,MJ,93681.235616,NaN,NaN,NaN,British Columbia
4,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Grid electricity,MJ,618213.376701,NaN,NaN,NaN,British Columbia
...,...,...,...,...,...,...,...,...,...,...
590,Underground mining and beneficiation at Timmin...,Doré,GRP-147b3123,Tailings,t,-373.160269,NaN,NaN,NaN,Ontario
591,Underground mining and beneficiation at Seabee...,Doré,GRP-14bfbb82,Tailings,t,-99.179545,NaN,NaN,NaN,Saskatchewan
592,Underground mining and beneficiation at Snow Lake,Cu concentrate,GRP-a13779f8,Tailings,t,-0.006414,NaN,NaN,NaN,Manitoba
593,Underground mining and beneficiation at Snow Lake,Zn concentrate,GRP-a13779f8,Tailings,t,-0.002398,NaN,NaN,NaN,Manitoba
594,Underground mining and beneficiation at Snow Lake,Doré,GRP-a13779f8,Tailings,t,-48.146845,NaN,NaN,NaN,Manitoba

In [148]:
#technosphere_stream_df.to_csv(r'technosphere_stream_df.csv', index=False)

# Map MetalliCan flows to EI and RI flows

In [149]:
from utils.conversion_functions import map_technosphere_to_ecoinvent, map_biosphere_to_ecoinvent
from utils.constants import CA_provinces

## Technosphere flows

In [150]:
mapping_technosphere = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='technosphere')

In [151]:
technosphere_stream_df

,activity_name,functional_unit,site_id,subflow_type,unit,value_normalized,value_min_normalized,value_mean_normalized,value_max_normalized,province
0,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Acetylene,MJ,20.073290,NaN,NaN,NaN,British Columbia
1,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Aviation fuel,MJ,78960.609903,NaN,NaN,NaN,British Columbia
2,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Diesel,MJ,311863.781032,NaN,NaN,NaN,British Columbia
3,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Generated on-site,MJ,93681.235616,NaN,NaN,NaN,British Columbia
4,Underground mining and beneficiation at Brucejack,Doré,BC-MAIN-857b7b89,Electricity consumption|Grid electricity,MJ,618213.376701,NaN,NaN,NaN,British Columbia
...,...,...,...,...,...,...,...,...,...,...
590,Underground mining and beneficiation at Timmin...,Doré,GRP-147b3123,Tailings,t,-373.160269,NaN,NaN,NaN,Ontario
591,Underground mining and beneficiation at Seabee...,Doré,GRP-14bfbb82,Tailings,t,-99.179545,NaN,NaN,NaN,Saskatchewan
592,Underground mining and beneficiation at Snow Lake,Cu concentrate,GRP-a13779f8,Tailings,t,-0.006414,NaN,NaN,NaN,Manitoba
593,Underground mining and beneficiation at Snow Lake,Zn concentrate,GRP-a13779f8,Tailings,t,-0.002398,NaN,NaN,NaN,Manitoba
594,Underground mining and beneficiation at Snow Lake,Doré,GRP-a13779f8,Tailings,t,-48.146845,NaN,NaN,NaN,Manitoba

In [152]:
# Apply the function
#mapped_technosphere_ore_df = map_technosphere_to_ecoinvent(technosphere_ore_df, mapping_technosphere, CA_provinces)
mapped_technosphere_stream_df = map_technosphere_to_ecoinvent(technosphere_stream_df, mapping_technosphere, CA_provinces)

⚠️ Les flux suivants n'ont pas trouvé de correspondance dans Ecoinvent:
 - Other

In [153]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
#mapped_technosphere_ore_df = mapped_technosphere_ore_df[(mapped_technosphere_ore_df["Activity"] != "No mapping") & (~mapped_technosphere_ore_df["Amount"].isna())]
mapped_technosphere_stream_df = mapped_technosphere_stream_df[(mapped_technosphere_stream_df["Activity"] != "No mapping")]

In [154]:
technosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Amount_min', 'Amount_mean', 'Amount_max', 'Activity', 'Product', 'Unit', 'Location', 'Database']

In [155]:
#mapped_technosphere_ore_df = mapped_technosphere_ore_df[technosphere_col_for_lci]
mapped_technosphere_stream_df = mapped_technosphere_stream_df[technosphere_col_for_lci]

In [156]:
mapped_technosphere_stream_df

,site_id,activity_name,functional_unit,Amount,Amount_min,Amount_mean,Amount_max,Activity,Product,Unit,Location,Database
0,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,0.418194,NaN,NaN,NaN,consumption market for acetylene,acetylene,kilogram,CA,Regioinvent
1,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,1832.032712,NaN,NaN,NaN,consumption market for kerosene,kerosene,kilogram,CA,Regioinvent
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,7252.646071,NaN,NaN,NaN,consumption market for diesel,diesel,kilogram,CA,Regioinvent
3,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,2178.633386,NaN,NaN,NaN,consumption market for diesel,diesel,kilogram,CA,Regioinvent
4,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,171726.075353,NaN,NaN,NaN,"market for electricity, medium voltage","electricity, medium voltage",kilowatt hour,CA-BC,ecoinvent-3.10-cutoff regionalized
...,...,...,...,...,...,...,...,...,...,...,...,...
693,GRP-147b3123,Underground mining and beneficiation at Timmin...,Doré,-373160.268666,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
694,GRP-14bfbb82,Underground mining and beneficiation at Seabee...,Doré,-99179.545258,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
695,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Cu concentrate,-6.414233,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
696,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,-2.397728,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
697,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,-48146.844591,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized

In [157]:
mapped_technosphere_stream_df.columns

Index(['site_id', 'activity_name', 'functional_unit', 'Amount', 'Amount_min',
       'Amount_mean', 'Amount_max', 'Activity', 'Product', 'Unit', 'Location',
       'Database'],
      dtype='object')

## Biosphere flows mapping

In [158]:
mapping_biosphere = pd.read_excel(r'data/Mappings/MAPPINGS_RI.xlsx', sheet_name='biosphere')

In [159]:
biosphere_stream_df.to_csv(r'biosphere_stream_df.csv', index=False)

In [160]:
#mapped_biosphere_ore_df = map_biosphere_to_ecoinvent(biosphere_ore_df, mapping_biosphere, CA_provinces)
mapped_biosphere_stream_df = map_biosphere_to_ecoinvent(biosphere_stream_df, mapping_biosphere, CA_provinces)

Index(['activity_name', 'functional_unit', 'site_id', 'substance_name', 'unit',
       'value_normalized', 'value_min_normalized', 'value_mean_normalized',
       'value_max_normalized', 'province', 'Type', 'substance_id',
       'compartment_name', 'release_pathway', 'flow_direction',
       'MetalliCan_unit', 'DB_to_map', 'Flow name', 'Compartments', 'Unit',
       'Comment', 'Alternatives'],
      dtype='object')
⚠️ 1 biosphere flows could not be mapped to Ecoinvent:
   - PFCs
⚠️ No conversion defined for tco2eq → nan (flow: PFCs)
✅ Mapped 16621 biosphere flows (120 unique flows).

In [161]:
# Drop rows where ecoinvent_flow_name is "No mapping" and Amount is NaN for now
#mapped_biosphere_ore_df = mapped_biosphere_ore_df[(mapped_biosphere_ore_df["Flow Name"] != "No mapping") & (~mapped_biosphere_ore_df["Amount"].isna())]
mapped_biosphere_stream_df = mapped_biosphere_stream_df[(mapped_biosphere_stream_df["Flow Name"] != "No mapping") & (~mapped_biosphere_stream_df["Amount"].isna())]

In [162]:
biosphere_col_for_lci = ['site_id', 'activity_name', 'functional_unit', 'Amount', 'Unit', 'Flow Name', 'Compartments', 'Database']

In [163]:
#mapped_biosphere_ore_df = mapped_biosphere_ore_df[biosphere_col_for_lci]
mapped_biosphere_stream_df = mapped_biosphere_stream_df[biosphere_col_for_lci]

In [164]:
#mapped_biosphere_ore_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/biosphere_ore_df.csv', index=False)
#mapped_biosphere_stream_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/biosphere_stream_df.csv', index=False)

In [165]:
#mapped_technosphere_ore_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/technosphere_ore_df.csv', index=False)
#mapped_technosphere_stream_df.to_csv(r'data/MetalliCan/data_for_lci_initialization/technosphere_stream_df.csv', index=False)

In [166]:
# Add province and commodities from NRCan to production table
#mapped_biosphere_ore_df = mapped_biosphere_ore_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')
mapped_biosphere_stream_df = mapped_biosphere_stream_df.merge(production_df[['site_id', 'province', 'commodities']], on=['site_id'], how='left')

In [167]:
mapped_technosphere_stream_df

,site_id,activity_name,functional_unit,Amount,Amount_min,Amount_mean,Amount_max,Activity,Product,Unit,Location,Database
0,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,0.418194,NaN,NaN,NaN,consumption market for acetylene,acetylene,kilogram,CA,Regioinvent
1,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,1832.032712,NaN,NaN,NaN,consumption market for kerosene,kerosene,kilogram,CA,Regioinvent
2,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,7252.646071,NaN,NaN,NaN,consumption market for diesel,diesel,kilogram,CA,Regioinvent
3,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,2178.633386,NaN,NaN,NaN,consumption market for diesel,diesel,kilogram,CA,Regioinvent
4,BC-MAIN-857b7b89,Underground mining and beneficiation at Brucejack,Doré,171726.075353,NaN,NaN,NaN,"market for electricity, medium voltage","electricity, medium voltage",kilowatt hour,CA-BC,ecoinvent-3.10-cutoff regionalized
...,...,...,...,...,...,...,...,...,...,...,...,...
693,GRP-147b3123,Underground mining and beneficiation at Timmin...,Doré,-373160.268666,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
694,GRP-14bfbb82,Underground mining and beneficiation at Seabee...,Doré,-99179.545258,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
695,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Cu concentrate,-6.414233,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
696,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,-2.397728,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized
697,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,-48146.844591,NaN,NaN,NaN,"market for sulfidic tailings, from copper mine...","sulfidic tailings, from copper mine operation",kilogram,CA,ecoinvent-3.10-cutoff regionalized

In [168]:
mapped_biosphere_stream_df

,site_id,activity_name,functional_unit,Amount,Unit,Flow Name,Compartments,Database,province,commodities
0,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,0.087684,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
1,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,0.087684,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
2,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,0.087684,kilogram,"Ammonia, CA-ON","('air', 'low population density long term')",biosphere3_spatialized_flows,Ontario,"Gold, silver"
3,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,0.087684,kilogram,Ammonia,"('soil', 'industrial')",biosphere3,Ontario,"Gold, silver"
4,ON-MAIN-1f126a43,Underground mining and beneficiation at Macassa,Doré,0.087684,kilogram,Ammonium,"('water',)",biosphere3,Ontario,"Gold, silver"
...,...,...,...,...,...,...,...,...,...,...
11537,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,0.000185,square meter,"Transformation, to mineral extraction site, CA-MB","('natural resource', 'land')",biosphere3_spatialized_flows,Manitoba,"Gold, zinc, copper, silver"
11538,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Zn concentrate,0.003696,square meter-year,"Occupation, mineral extraction site, CA-MB","('natural resource', 'land')",biosphere3_spatialized_flows,Manitoba,"Gold, zinc, copper, silver"
11539,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,3.710729,square meter,"Transformation, from unspecified, natural (non...","('natural resource', 'land')",biosphere3_spatialized_flows,Manitoba,"Gold, zinc, copper, silver"
11540,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,3.710729,square meter,"Transformation, to mineral extraction site, CA-MB","('natural resource', 'land')",biosphere3_spatialized_flows,Manitoba,"Gold, zinc, copper, silver"
11541,GRP-a13779f8,Underground mining and beneficiation at Snow Lake,Doré,74.214576,square meter-year,"Occupation, mineral extraction site, CA-MB","('natural resource', 'land')",biosphere3_spatialized_flows,Manitoba,"Gold, zinc, copper, silver"

In [169]:
mapped_biosphere_stream_df.to_csv(r'test_bio.csv', index=False)

In [170]:
mapped_technosphere_stream_df.to_csv(r'test_tech.csv', index=False)

# LCI creation

In [171]:
from core.lci_database_builder import LCIDatabaseBuilder

## Usable ore basis

In [172]:
# Step 1 — initialize the builder
builder_uo = LCIDatabaseBuilder(db_name='metallican_lci', project_name='metallican')

📂 Active Brightway project: metallican
🆕 Database 'metallican_lci' created.

In [173]:
# Step 2 — create the activity shells from the main dataframe
builder_uo.build_lci_entries(df=mapped_biosphere_stream_df)
print(len(builder_uo.lcis))

✅ Created 58 base LCI activities with production exchanges.
58

In [174]:
# Step 3a — Populate with the technosphere exchanges
builder_uo.populate_technosphere_exchanges(technosphere_df=mapped_technosphere_stream_df)

⚙️ Populating technosphere exchanges
   ✅ Cached 218246 activities from Regioinvent
   ✅ Cached 20769 activities from ecoinvent-3.10-cutoff regionalized
✅ Added 692 technosphere exchanges.

In [175]:
# Step 3b — Populate with the biosphere exchanges
builder_uo.populate_biosphere_exchanges(biosphere_df=mapped_biosphere_stream_df)

🌱 Populating biosphere exchanges
   ✅ Cached 110559 biosphere flows from biosphere3_spatialized_flows
   ✅ Cached 4362 biosphere flows from biosphere3
✅ Added 11542 biosphere exchanges.

In [176]:
# Step 4 - Consolidate duplicate flows
builder_uo.consolidate_exchanges()

🧮 Consolidation: 12292 → 1538 exchanges (summed duplicates).

In [177]:
builder_uo.write_to_database()

🧱 Writing 58 activities to database 'metallican_lci'...
✅ Database 'metallican_lci' processed successfully with 58 activities.